export const CHANGE_METHOD_ADDRESS = 'CHANGE_METHOD_ADDRESS';
export const CHANGE_CURRENT_CATEGORY = 'CHANGE_CURRENT_CATEGORY';
export const CHANGE_FILTER_TEXT = 'CHANGE_FILTER_TEXT';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
